name: GitHub Classroom Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GitHub Classroom Autograding
        uses: education/autograding@v1
